kind: ConfigMap
apiVersion: v1
metadata:
  name: csa-profiles-converter-configmap
  labels:
    app: gridcapa
    component: csa-profiles-converter
    region: swe
    process: csa
data:
  application.yml: |-
    server:
      port: 8080
    spring:
      application:
        name: csa-profiles-converter
      servlet:
        multipart:
          max-file-size: 500MB
          max-request-size: 500MB
    s3:
      artifacts:
        bucket: swe-csa-bucket
        user:  ${MINIO_ACCESS_KEY}
        secret: ${MINIO_SECRET_KEY}
        url: http://gridcapa-minio:9000/ 
