kind: ConfigMap
apiVersion: v1
metadata:
  name: csa-runner-configmap
  labels:
    app: gridcapa
    component: runner
    region: swe
    process: csa
data:
  application.yml: |-
    server:
      port: 8080
    spring:
      application:
        name: swe-csa-runner
      rabbitmq:
        host: gridcapa-rabbitmq
        virtual-host: vhost
        username: ${RABBITMQ_USER}
        password: ${RABBITMQ_PASSWORD}
        port: 5672
        template:
          reply-timeout: 18000000
      cloud:
        function:
          definition: interrupt;request
        stream:
          default:
            binder: rabbit
          bindings:
            interrupt-in-0:
              destination: csa-interrupt
            request-in-0:
              destination: csa-request
            request-out-0:
              destination: csa-response
            acknowledgement:
              destination: csa-request-ack
            stop-rao:
              destination: stop-rao-runner
    rao-runner-server:
      amqp:
        client-app-id: swe-csa-runner
        queue-name: swe-csa-rao-request-queue
    dichotomy-parameters:
      index:
        precision: 50
        max-iterations-by-border: 10
    s3:
      inputs:
        bucket: swe-csa-bucket
        user: ${MINIO_ACCESS_KEY}
        secret: ${MINIO_SECRET_KEY}
        url: http://gridcapa-minio:9000/
      artifacts:
        bucket: swe-csa-bucket
        user: ${MINIO_ACCESS_KEY}
        secret: ${MINIO_SECRET_KEY}
        url: http://gridcapa-minio:9000/
      outputs:
        bucket: swe-csa-bucket
        user: ${MINIO_ACCESS_KEY}
        secret: ${MINIO_SECRET_KEY}
        url: http://gridcapa-minio:9000/
    logging:
      config: /config/logback.xml

  logback.xml: |-
    <?xml version="1.0" encoding="UTF-8"?>
    <configuration>
        <appender name="STDOUT" class="ch.qos.logback.core.ConsoleAppender">
            <encoder>
                <pattern>%d{yyyy-MM-dd'T'HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n</pattern>
            </encoder>
        </appender>
        
        <root level="info">
            <appender-ref ref="STDOUT"/>
        </root>
        
        <logger name="org.springframework.amqp" level="OFF"/>
        <logger name="com.powsybl" level="OFF"/>
        <logger name="com.powsybl.openloadflow" level="OFF"/>
        <logger name="com.powsybl.openrao" level="INFO"/>
        <logger name="com.powsybl.openrao.commons.logs.TechnicalLogs" level="OFF"/>
    </configuration>