apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - swe-csa-ingress.yaml
  - minio-deployment.yaml
  - minio-pv-claim.yaml
  - minio-service.yaml
  - rabbitmq.yaml
  - rabbitmq-service.yaml
  - rabbitmq-configmap.yaml
  - rao-runner-deployment.yaml
  - rao-runner-service.yaml
  - rao-runner-spring-config-map.yaml
  - rao-runner-itools-config-map.yaml
  - csa-runner-deployment.yaml
  - csa-runner-service.yaml
  - csa-runner-spring-config-map.yaml
  - csa-runner-itools-config-map.yaml
  - csa-profiles-converter-deployment.yaml
  - csa-profiles-converter-service.yaml
  - csa-profiles-converter-spring-config-map.yaml
configMapGenerator:
  - name: env-configmap
    envs: [ env.properties ]

patches:
  - patch: |-
      kind: Deployment
      apiVersion: apps/v1
      metadata:
        name: rao-runner
      spec:
        replicas: 2
        template:
          spec:
            containers:
              - name: rao-runner
                resources:
                  requests:
                    cpu: "1.0"
                    memory: "10Gi"
                  limits:
                    cpu: "2.0"
                    memory: "20Gi"
  - patch: |-
      kind: Deployment
      apiVersion: apps/v1
      metadata:
        name: csa-runner
      spec:
        replicas: 2
        template:
          spec:
            containers:
              - name: csa-runner
                resources:
                  requests:
                    cpu: "1.0"
                    memory: "10Gi"
                  limits:
                    cpu: "2.0"
                    memory: "20Gi"
images:
  - name: minio
    newName: docker.io/bitnami/minio
    newTag: 2021.6.17
  - name: rabbitmq
    newName: docker.io/rabbitmq
    newTag: management
  - name: rao-runner
    newName: docker.io/farao/gridcapa-rao-runner
    newTag: 6.1.0-SNAPSHOT
  - name: csa-runner
    newName: docker.io/farao/gridcapa-swe-csa
    newTag: 6.1.0-SNAPSHOT
  - name: csa-profiles-converter
    newName: docker.io/farao/csa-profiles-converter
    newTag: do-not-read-is-combinable-with-ra
