kind: ConfigMap
apiVersion: v1
metadata:
  name: rao-runner
  labels:
    app: gridcapa
    component: rao-runner
data:
  application.yml: |-
    spring:
      rabbitmq:
        host: gridcapa-rabbitmq
        virtual-host: vhost
        port: 5672
        username: ${RABBITMQ_USER}
        password: ${RABBITMQ_PASSWORD}
    minio-adapter:
      bucket: swe-csa-bucket
      base-path:
      access-key: ${MINIO_ACCESS_KEY}
      secret-key: ${MINIO_SECRET_KEY}
      url: http://gridcapa-minio:9000/
    rao-runner:
      messages:
        rao-request:
          queue-name: swe-csa-rao-request-queue
      url:
        whitelist:
          - http://gridcapa-minio:9000/
    server:
      port: 8080
    logging:
      config: /config/logback.xml

  logback.xml: |-
    <?xml version="1.0" encoding="UTF-8"?>
    <configuration>
      <appender name="STDOUT" class="ch.qos.logback.core.ConsoleAppender">
        <encoder>
          <pattern>%d{yyyy-MM-dd'T'HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n</pattern>
        </encoder>
      </appender>
      
      <root level="info">
         <appender-ref ref="STDOUT" />
      </root>
    
      <logger name="org.springframework.amqp" level="OFF"/>
      <logger name="com.powsybl" level="OFF"/>
      <logger name="com.powsybl.openloadflow" level="OFF"/>
      <logger name="com.powsybl.openrao" level="INFO"/>
      <logger name="com.powsybl.openrao.commons.logs.TechnicalLogs" level="OFF"/>
    </configuration>