kind: ConfigMap
apiVersion: v1
metadata:
  name: rao-runner
  labels:
    app: gridcapa
    component: rao-runner
data:
  application.yml: |-
    spring:
      rabbitmq:
        host: gridcapa-rabbitmq
        virtual-host: vhost
        port: 5672
        username: ${RABBITMQ_USER}
        password: ${RABBITMQ_PASSWORD}

    minio:
      bucket: gridcapa
      base-path:
      access:
        name: ${MINIO_ACCESS_KEY}
        secret: ${MINIO_SECRET_KEY}
      url: http://gridcapa-minio:9000/

    rao-runner:
      messages:
        rao-request:
          queue-name: swe-csa-rao-request-queue
      url:
        whitelist:
          - http://gridcapa-minio:9000/

    server:
      port: 8080