spring:
  rabbitmq:
    host: rabbitmq
    port: 5672
    username: guest
    password: guest
    template:
      reply-timeout: 7200000
  cloud:
    stream:
      bindings:
        stop-in-0:
          binder: rabbit
          destination: stop-rao-runner
minio-adapter:
  bucket: swe-csa-bucket
  base-path:
  access-key: minioadmin
  secret-key: minioadmin
  url: http://minio:9000


rao-runner:
  messages:
    rao-request:
      queue-name: swe-csa-rao-request-queue
  url:
    whitelist:
      - http://minio:9000/

